### PR TITLE
Remove jquery use vanilla js

### PR DESCRIPTION
**Pull request by cmd430**
Rewrote the JS to use vanilla JS so you dont need to pull in jQuery
Tested in Latest Firefox, Latest Chrome and on my iPhone running iOS 14.2beta4 everything seems to be working fine

### CODE REVIEW

**Comment by cmd430** [comment]
Oh, I forgot I also made it reset the form on page load so it starts clean every time

**Comment by WhiskeeDev** [comment]
I come from a background of working with large frameworks and tons of dependencies and libraries, so forgive me if my knowledge is lacking, but is removing jQuery really necessary?
I understand removing the need for external dependencies being seen as good practise and a benefit to load times and compatibility, but in my experience jQuery is very lightweight and very well supported.

I'd be interested in hearing your opinion and understanding why removing jQuery may be a better option.

**Comment by cmd430** [comment]
Frameworks can be good, but for this project I think its unnecessary bloat when you can do the same with Vanilla JS with only a couple extra lines of code over all, The benefit of doing it with Vanilla is you don't have to load the jQuery lib for little gain and without the overhead of jQuery it should be a touch faster (not that this was/is a huge issue in this case) the main thing though is that jQuery really just isnt needed anymore for almost everything, this may be an interesting read for you http://youmightnotneedjquery.com/

**Comment by WhiskeeDev** [comment]
Thanks for the link, I'll make sure to have a read when I have some free time (23:30 when posting this, so I won't be able to take in any information if I read now).
I agree with your point about VanillaJS being more than suitable and being better for speed, but in the use case of this app, I think the ease of development is worth keeping it.
Regardless, I'm going to do a bit of research on the Vanilla alternatives, best I have a knowledge of it in case dropping jQuery becomes a more common practice.

**Comment by cmd430** [comment]
yeah that link has some good examples showing how to do something in VanillaJS vs jQuery, its diffidently more and more common to not use jQuery these days so getting caught up on all the new VanillaJS features will only benefit you

**Comment by zuffdaddy** [comment]
While I do appreciate the work, I grew up on jquery and learning VanillaJS isnt a possibility atm. And if I merged your pull I would lose complete control of how my project is coded. I'll definitely look into VanillaJS in the future but for now I will deal with the bloat of jquery (which is so minuscule and non-impacting on a project of this scope).

**Comment by cmd430** [comment]
fair enough, I just removed the console.logs i left in because it was annoying me but feel free to close this pull request if you want then

**Pull request closed without merging**
